spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: ""

# Gateway configuration for development
gateway:
  services:
    user-service-url: http://localhost:8081
    auth-service-url: http://localhost:8082
    organization-service-url: http://localhost:8083
    chat-service-url: http://localhost:8084

  cors:
    allowed-origins: "*"

  rate-limit:
    replenish-rate: 100  # Lenient for development
    burst-capacity: 200

  jwt:
    secret: dev-super-secret-jwt-key-for-development-environment-only

logging:
  level:
    com.iam.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    io.lettuce: DEBUG  # Redis logging