spring:
  data:
    redis:
      host: localhost
      port: 6370  # Different port for test isolation
      password: ""

# Gateway configuration for testing
gateway:
  services:
    user-service-url: http://localhost:18081
    auth-service-url: http://localhost:18082
    organization-service-url: http://localhost:18083
    chat-service-url: http://localhost:18084

  rate-limit:
    replenish-rate: 1000  # Very lenient for testing
    burst-capacity: 2000

  jwt:
    secret: test-jwt-secret-for-testing-only
    expiration: 300000  # 5 minutes for testing

logging:
  level:
    com.iam.gateway: INFO