spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL:true}

# Gateway configuration for production
gateway:
  services:
    user-service-url: ${USER_SERVICE_URL}
    auth-service-url: ${AUTH_SERVICE_URL}
    organization-service-url: ${ORGANIZATION_SERVICE_URL}
    chat-service-url: ${CHAT_SERVICE_URL}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://yourapp.com,https://admin.yourapp.com}
    allow-credentials: true

  rate-limit:
    replenish-rate: ${RATE_LIMIT_REPLENISH:10}
    burst-capacity: ${RATE_LIMIT_BURST:20}

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:3600000} # 1 hour

logging:
  level:
    root: WARN
    com.iam.gateway: INFO